language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t joaquimcsantos/docker-react -f Dockerfile.dev .

script:
  - docker run joaquimcsantos/docker-react npm run test -- --coverage
